### ISSUE TITLE
Debug geonode raster upload

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/helm-charts#16]
We can use the upload of getiffs to geonode to check for problems with the configuration. Especially the celery task runner could need a closer look for bigger images.

**Comment by knl88** [comment]
looks to be a problem when completing uploads

```bash
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/upload/tasks.py", line 94, in finalize_incomplete_session_uploads
    raise NotFound
gsimporter.api.NotFound
```

**Comment by knl88** [comment]
The uploads should list here `https://geonode.seabee.sigma2.no/geoserver/rest/imports/`

**Comment by knl88** [comment]
Looks like the problem starts here

```bash
Uploading coverage
'NoneType' object has no attribute 'import_session'
Traceback (most recent call last):
  File "/usr/src/geonode/./geonode/upload/upload.py", line 320, in save_step
    import_session = upload.get_session.import_session
AttributeError: 'NoneType' object has no attribute 'import_session'
'NoneType' object has no attribute 'import_session'
Traceback (most recent call last):
  File "/usr/src/geonode/./geonode/upload/views.py", line 695, in view
    resp = _steps[step](req, upload_session)
  File "/usr/src/geonode/./geonode/upload/views.py", line 158, in save_step_view
    import_session, upload = save_step(
  File "/usr/src/geonode/./geonode/upload/upload.py", line 438, in save_step
    raise e
  File "/usr/src/geonode/./geonode/upload/upload.py", line 320, in save_step
    import_session = upload.get_session.import_session
```

**Comment by knl88** [comment]
Bumped the resources a bit and some files work now, but others give an error, but at least geonode report the error. So probably best to just use geoserver for most of the uploads.
